version: '{build}'

image: Visual Studio 2017

build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1

test: off

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

artifacts:
- path: .\src\Unity.AutoFactory\bin\Release\Unity.AutoFactory.*.nupkg
